#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/opt/anaconda3/envs/python3_8/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/opt/anaconda3/envs/python3_8/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/Users/katedoxey/Desktop/research/visual_vergil/single_cell_network/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
